[ci] pull-requests: fix dogfood - use help plugin

diff --git a/.github/workflows/pull-requests.yml b/.github/workflows/pull-requests.yml
--- a/.github/workflows/pull-requests.yml
+++ b/.github/workflows/pull-requests.yml
@@ -138,7 +138,7 @@ jobs:
           echo "Determined PR number: ${pr_number}"
 
           current_pmd_version=$(./mvnw --batch-mode --no-transfer-progress \
-              maven:evaluate -Dexpression=project.version -q -DforceStdout || echo "failed_to_determine_current_pmd_version")
+              help:evaluate -Dexpression=project.version -q -DforceStdout || echo "failed_to_determine_current_pmd_version")
           echo "Determined current pmd version: ${current_pmd_version}"
 
           new_version="${current_pmd_version}-pr-${pr_number}-dogfood-SNAPSHOT"
